language: go
os:
  - linux
  - osx
go:
  - 1.14.x
go_import_path: github.com/kataras/iris/v12
env:
 global:
   - GO111MODULE=on
install:
  - go get ./...
script:
  - go test -count=1 -v -cover ./...
after_script:
  # examples
  - cd ./_examples
  - go get ./...
  - go test -count=1 -v -cover ./...
  - cd ../
  # make sure that the _benchmarks code is working
  - cd ./_benchmarks
  - go get ./...
  - go test -count=1 -v -cover ./...