language: go
os:
  - linux
  - osx
go:
  - go1.9
go_import_path: github.com/kataras/iris
install:
  - go get ./... # for iris-contrib/httpexpect, kataras/golog
script:
  - go test -v -cover ./...
after_script:
  # examples
  - cd ./_examples
  - go get ./...
  - go test -v -cover ./...
  - cd ../
  # typescript examples
  - cd ./typescript/_examples
  - go get ./...
  - go test -v -cover ./...