sudo: false
language: go

os:
  - linux
  - osx
go:
# We support the latest two major Go versions:
# https://golang.org/doc/devel/release.html
  - 1.15.x
  - 1.16.x
# - master
go_import_path: github.com/kataras/iris/v12
env:
 global:
   - GO111MODULE=on
addons:
  hosts:
    - mydomain.com
    - www.mydomain.com
    - myotherdomain.com
    - mymy.com
    - testdomain.com
    - testdomain1.com
    - testdomain2.com
install:
  - go get ./...
script:
  - go test -count=1 -v -cover -race ./...
after_script:
  # examples
  - cd ./_examples
  - go get ./...
  - go test -count=1 -v -cover -race ./...
  - cd ../
