language: go
os:
  - linux
  - osx
go:
# - go1.8 works of course but
# we must encourage users to update to the latest go version,
# so examples are running on go 1.9 mode.
  - go1.9
  - tip
go_import_path: github.com/kataras/iris
install:
  - go get ./... # for iris-contrib/httpexpect, kataras/golog, boltdb/bolt(sessiondb, optional)
script:
  - go test -v -cover ./...
after_script:
  # examples
  - cd ./_examples
  - go get ./...
  - go test -v -cover ./...
  - cd ../
  # typescript examples
  - cd ./typescript/_examples
  - go get ./...
  - go test -v -cover ./...