[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/Joker/jade"

[[constraint]]
  branch = "master"
  name = "github.com/iris-contrib/i18n"

[[constraint]]
  branch = "master"
  name = "github.com/aymerick/raymond"

[[constraint]]
  branch = "master"
  name = "github.com/eknkc/amber"

[[constraint]]
  name = "github.com/fatih/structs"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/flosch/pongo2"

[[constraint]]
  branch = "master"
  name = "github.com/iris-contrib/formBinder"

[[constraint]]
  branch = "master"
  name = "github.com/iris-contrib/httpexpect"

[[constraint]]
  branch = "master"
  name = "github.com/json-iterator/go"

[[constraint]]
  branch = "master"
  name = "github.com/kataras/golog"

[[constraint]]
  branch = "v2"
  name = "github.com/kataras/survey"

[[constraint]]
  name = "github.com/klauspost/compress"
  version = "1.2.1"

[[constraint]]
  branch = "master"
  name = "github.com/microcosm-cc/bluemonday"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/russross/blackfriday.v2"

[[constraint]]
  branch = "master"
  name = "github.com/ryanuber/columnize"

[[constraint]]
  branch = "v2"
  name = "github.com/iris-contrib/go.uuid"

[[constraint]]
  branch = "master"
  name = "github.com/valyala/bytebufferpool"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"

[[constraint]]
  branch = "master"
  name = "github.com/Shopify/goreferrer"